require:
  - rubocop-rails

Layout/LineLength:
  Max: 120

AllCops:
  NewCops: enable
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/*
    - node_modules/**/*
    - config/initializers/saml_idp.rb
    - config/initializers/devise.rb
    - app/models/setting.rb
    - config/deploy.rb

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - app/policies/*

Rails/InverseOf:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/routes.rb
    - Guardfile
    - lib/tasks/auto_annotate_models.rake
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/doorkeeper_openid_connect.rb
    - lib/tasks/*
    - app/admin/*
    - spec/models/*.rb
    - spec/controllers/*.rb
    - spec/controllers/admin/*.rb

Naming/AccessorMethodName:
  Enabled: false

Layout/HashAlignment:
  Enabled: False

Style/GlobalVars:
  AllowedVariables:
    - $redis

Rails/Output:
  Exclude:
    - db/seeds.rb
