Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/*
    - node_modules/**/*
    - config/initializers/saml_idp.rb
    - config/initializers/devise.rb
    - app/models/setting.rb
Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - app/policies/*

Rails/InverseOf:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - Guardfile
    - lib/tasks/auto_annotate_models.rake
    - config/initializers/simple_form_bootstrap.rb
    - lib/tasks/*
    - app/admin/*

Layout/AlignHash:
  Enabled: False

GlobalVars:
  AllowedVariables:
    - $redis

Rails/Output:
  Exclude:
    - db/seeds.rb
