# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'].presence || "postgresql" %>
  encoding: <%= ENV['DATABASE_ENCODING'].presence || "utf8" %>
  reconnect: <%= ENV['DATABASE_RECONNECT'].presence || "true" %>
  pool: <%= ENV['DATABASE_POOL'].presence || ENV['RAILS_MAX_THREADS'] || "10" %>
  username: <%= ENV['DATABASE_USERNAME'].presence || `whoami` %>
  password: <%= ENV['DATABASE_PASSWORD'] || "" %>
  host: <%= ENV['DATABASE_HOST'] || "" %>
  port: <%= ENV['DATABASE_PORT'] || "" %>
  socket: <%= ENV['DATABASE_SOCKET'] || "" %>
  strict: false


development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'].presence || "EyedP_development" %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'].presence || "EyedP_test" %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'].presence || "EyedP_production" %>
  pool: <%= ENV['DATABASE_POOL'].presence || "20" %>
